version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/opt/app'
      - gem_cache:/usr/local/bundle
    environment:
      - RACK_ENV=development
      - REDIS_URL=redis://redis:6379
      - HOST=localhost:4567
    ports:
      - '4567:4567'
    depends_on: [ redis ]
    command: bundle exec rackup
    stdin_open: true
    tty: true


  redis:
    image: redis:4.0

volumes:
  gem_cache:
    driver: local
