version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: apipa_base:latest
    volumes:
      - '.:/opt/app'
      - gem_cache:/usr/local/bundle
    ports:
      - '4567:4567'
    depends_on: [ redis ]
    stdin_open: true
    tty: true

  redis:
    image: redis:4.0

volumes:
  gem_cache:
    driver: local
